/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.modules;

import org.junit.Test;
import org.mule.api.MuleEvent;
import org.mule.construct.Flow;
import org.mule.tck.AbstractMuleTestCase;
import org.mule.tck.FunctionalTestCase;

public class weatherSimpleConnectorTest extends FunctionalTestCase
{
    @Override
    protected String getConfigResources()
    {
        return "weather-config-simple.xml";
    }

    @Test
    public void testFlow() throws Exception
    {
    	Flow flow = lookupFlowConstruct("normalConfig");
        MuleEvent event = AbstractMuleTestCase.getTestEvent("");
        MuleEvent responseEvent = flow.process(event);
    }

    protected Flow lookupFlowConstruct(String name)
    {
        return (Flow) AbstractMuleTestCase.muleContext.getRegistry().lookupFlowConstruct(name);
    }
}
